### ISSUE TITLE
Http is not supproted.

### ISSUE THREAD

**Issue by abisogullari** [pste/youtube.get-video-info#5]
Hi
previously worked properly but now doesn't work. I haven't changed/updated anything in my code.

code does not throw err. Response is:
`{ reason: 'HTTP+is+not+supported.',
  errorcode: '180',
  status: 'fail' }`

Code:
`var yt = require('youtube.get-video-info');
yt.retrieve('ml-v1bgMJDQ', function(err, res) {
  if (err) throw err;
  console.log(res);
});`

**Comment by pste** [comment]
Hi,
it's pretty old code (I surely need to add some auto-test and to improve the whole thing), but here's the fix for the _errorcode: 180_
See [this](https://github.com/pste/youtube.get-video-info/commit/f756fc5621806faa11f6ba0bc30b460d5457f1b9) for info
